#!/bin/sh

ghci    -XScopedTypeVariables -XDataKinds -XTypeFamilies \
        -XParallelListComp \
        -XFlexibleInstances -XFlexibleContexts \
        -XMultiParamTypeClasses \
        -XTypeOperators       -XBangPatterns \
        Datum.Console \
        $1 $2 $3 $4

